server:
  port: 9999
spring:
  application:
    name: easypoi-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://148.70.3.235:33306/leyou?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: root
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10


