server:
  port: 8090
  servlet:
    context-path:



# Logging configuration
#logging:
#  level:
#    org.springframework:
#      data: DEBUG
#      security: DEBUG

spring:
  #配置 redis 连接信息
  redis:
    port: 6379
    host: 148.70.3.235
    password: asdasdnc2.
    database: 0
  # 热部署生效
  devtools:
    restart:
      enabled: true
      # 设置启动的目录
      additional-paths: src/main
      #classpath目录下的WEB-INF文件夹内容修改不重启
      exclude: WEB-INF/**
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
#    cache: false

niici:
  security:
    browser:
    # 登录页 设置
      loginPage: /demoLogin.html
    # 返回 类型设置 (JSON 还是 VIEW)
      loginType: REDIRECT
    code:
      image:
        length: 4
        width: 60
        height: 30
        url: /user,/user/*