server:
  port: 10000
spring:
  application:
    name: redis-service
  #配置 redis 连接信息
  redis:
    port1: 6379
    host: 148.70.3.235
    password: asdasdnc2.
    database: 0
#  redis:
#    cluster:
#      nodes:
#      - 148.70.3.235:6379
#      - 148.70.3.235:6380
#      - 148.70.3.235:6381
#       # 获取失败 最大重定向次数
#       max-redirects: 3
#    lettuce:
#      pool:
#        # 连接池中的最大连接池
#        max-active: 10
#        # 连接池中的最大空闲连接
#        max-idle: 10
#        # 连接分配在池被耗尽时抛出异常之前应该阻塞的最长时间,使用负值可以无限制的阻塞
#        max-wait: -1ms
#        # 连接池中的最小空闲连接
#        min-idle: 3
#    # 连接超时时间
#    timeout: 6000ms


